name: Demo Payload
run-name: Demo payload

on:
  - workflow_dispatch
  - issues:
      types:
        - opened
  - push:
      branches:
        - main

jobs:
  show-payload:
    name: Show the github payload
    runs-on: ubuntu-latest
    steps:
      - uses: rabobank-actions/demo-show-payload@latest